// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBxvGKOo4Ypg2wK96nALQsNWgqm_4suD8E',
    appId: '1:1057311985129:web:fb804cbfa17e90627d4f78',
    messagingSenderId: '1057311985129',
    projectId: 'chat-app-f4213',
    authDomain: 'chat-app-f4213.firebaseapp.com',
    storageBucket: 'chat-app-f4213.firebasestorage.app',
    measurementId: 'G-12J981NLER',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyALN91JAYG296tuDs3c2OeyEhYDJQ9NEAA',
    appId: '1:1057311985129:android:c68efcbed94cbfe37d4f78',
    messagingSenderId: '1057311985129',
    projectId: 'chat-app-f4213',
    storageBucket: 'chat-app-f4213.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCp6M19rSx9FGeo0_EmmIRI7MPsP3CDgm0',
    appId: '1:1057311985129:ios:b616da6c7a17ccad7d4f78',
    messagingSenderId: '1057311985129',
    projectId: 'chat-app-f4213',
    storageBucket: 'chat-app-f4213.firebasestorage.app',
    iosClientId: '1057311985129-h0h560oau2tjotp9rlte8r9dttmkqpua.apps.googleusercontent.com',
    iosBundleId: 'com.example.bliFlutterRecipewhisper',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCp6M19rSx9FGeo0_EmmIRI7MPsP3CDgm0',
    appId: '1:1057311985129:ios:b616da6c7a17ccad7d4f78',
    messagingSenderId: '1057311985129',
    projectId: 'chat-app-f4213',
    storageBucket: 'chat-app-f4213.firebasestorage.app',
    iosClientId: '1057311985129-h0h560oau2tjotp9rlte8r9dttmkqpua.apps.googleusercontent.com',
    iosBundleId: 'com.example.bliFlutterRecipewhisper',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDEyrsD-Z-kOobUrPimqrhg_AI-dxIZIlw',
    appId: '1:1057311985129:web:f482cce3550bfa077d4f78',
    messagingSenderId: '1057311985129',
    projectId: 'chat-app-f4213',
    authDomain: 'chat-app-f4213.firebaseapp.com',
    storageBucket: 'chat-app-f4213.firebasestorage.app',
    measurementId: 'G-VZN431E76F',
  );
}
