class AppStrings {
  // English Strings
  static const Map<String, String> en = {
    // Common
    'app_name': 'Recipe Whisper',
    'ok': 'OK',
    'cancel': 'Cancel',
    'save': 'Save',
    'delete': 'Delete',
    'edit': 'Edit',
    'search': 'Search',
    
    // Auth
    'login': 'Login',
    'signup': 'Signup',
    'logout': 'Logout',
    'email': 'Email',
    'password': 'Password',
    'forgot_password': 'Forgot Password?',
    'dont_have_account': "Don't have an account? Signup",
    'already_have_account': 'Already have an account? Login',
    'login_success': 'Login successful',
    'signup_success': 'Signup successful',
    'login_failed': 'Login failed',
    'signup_failed': 'Signup failed',
    'password_reset_sent': 'Password reset email sent',
    'enter_email_first': 'Enter your email first',
    
    // Home
    'good_morning': 'Good Morning! 👋',
    'good_afternoon': 'Good Afternoon! 👋',
    'good_evening': 'Good Evening! 👋',
    'what_to_cook': 'What would you like to cook today?',
    'search_recipes': 'Search recipes...',
    'popular_recipes': 'Popular Recipes',
    
    // Navigation
    'home': 'Home',
    'recipes': 'Recipes',
    'ai': 'AI',
    'profile': 'Profile',
    
    // Profile
    'settings': 'Settings',
    'dark_theme': 'Dark Theme',
    'english_language': 'English Language',
    'account': 'Account',
    'preferences': 'Preferences',
    'edit_profile': 'Edit Profile',
    'display_name': 'Display Name',
    'change_password': 'Change Password',
    'name_updated': 'Name updated successfully!',
    'error_updating_name': 'Error updating name',
    'password_reset_dialog_title': 'Change Password',
    'password_reset_dialog_message': 'A password reset link will be sent to your email address.',
    'send_reset_link': 'Send Reset Link',
    
    // Recipe
    'add_recipe': 'Add Recipe',
    'edit_recipe': 'Edit Recipe',
    'recipe_name': 'Recipe Name',
    'recipe_description': 'Description',
    'ingredients': 'Ingredients',
    'instructions': 'Instructions',
    'cooking_time': 'Cooking Time',
    'servings': 'Servings',
    'category': 'Category',
    'minutes': 'minutes',
    'recipe_added': 'Recipe added successfully',
    'recipe_deleted': 'Recipe deleted',
    'recipe_updated': 'Recipe updated',
    'no_recipes': 'No recipes found',
    'add_your_first': 'Add your first recipe!',
    'recipe_details': 'Recipe Details',
    'add_ingredient': 'Add Ingredient',
    'add_instruction': 'Add Instruction',
    'enter_ingredient': 'Enter ingredient',
    'enter_instruction': 'Enter instruction',
    'step': 'Step',
    'start_cooking': 'Start Cooking',
    'resume_cooking': 'Resume Cooking',
    
    // AI
    'ai_suggestions': 'AI Suggestions',
    'get_suggestion': 'Get Suggestion',
    'generating': 'Generating...',
    'ai_assistant': 'AI Assistant',
    'type_message': 'Type your message...',
    'clear_chat': 'Clear chat',
    'chat_cleared': 'Chat cleared! Start a new conversation.',
    'ai_thinking': 'AI is thinking...',
    'how_to_use': 'How to use',
    'help': 'Help',
    'quick_actions': 'Quick Actions',
    'start_chatting': 'Start chatting!',
    'personalized_recommendations': 'Personalized recommendations just for you',
    'create_new_recipe': 'Create a new recipe',
    'create_new_recipe_desc': 'Let AI help you add recipes through conversation',
    'low_carb_dinner': 'Low-carb dinner ideas',
    'low_carb_dinner_desc': 'Healthy and delicious meal suggestions',
    'quick_breakfast': 'Quick breakfast recipes',
    'quick_breakfast_desc': 'Start your day right in under 15 minutes',
    'meal_prep': 'Meal prep for the week',
    'meal_prep_desc': 'Save time with batch cooking tips',
    'mexican_cuisine': 'Mexican cuisine night',
    'mexican_cuisine_desc': 'Authentic flavors and traditional recipes',
    'recipe_saved_tap': 'Recipe saved! Tap to view',
    'got_it': 'Got it!',
    
    // Nutrition
    'nutrition': 'Nutrition',
    'calories': 'Calories',
    'protein': 'Protein',
    'carbs': 'Carbs',
    'fat': 'Fat',
    
    // Reminders
    'reminders': 'Reminders',
    'set_reminder': 'Set Reminder',
    'reminder_time': 'Reminder Time',
    'reminder_set': 'Reminder set successfully',

    // Cooking timer
    'no_recipe': 'No Recipe',
    'no_active_timer': 'No active timer',
    'cooking': 'Cooking',
    'done': '✅ Done!',
    'pause': 'Pause',
    'resume': 'Resume',
    'finish': 'Finish',
    'stage_just_started': '🔥 Just started...',
    'stage_heating_up': '🍳 Heating up...',
    'stage_cooking_nicely': '🥘 Cooking nicely...',
    'stage_getting_close': '⏳ We are getting close...',
    'stage_almost_done': '🍲 Almost done...',
    'stage_ready_soon': '🍽 Ready soon...',

    'previous': 'Previous',
    'next': 'Next',
    'stop': 'Stop',
    'stop_cooking_confirmation': 'Are you sure you want to stop cooking?',
    'no_instructions_available': 'No instructions available',

    // Add to English (en) map: profile
'consumed_today': 'Consumed Today',
'kcal': 'kcal',
'over_limit': 'Over Limit',
'remaining': 'Remaining',
'view_diet_profile': 'View Diet Profile',
'diet_calorie_tracker': 'Diet & Calorie Tracker',
'height': 'Height',
'daily_goal': 'Daily Goal',
'edit_diet_profile': 'Edit Diet Profile',
'diet_profile': 'Diet Profile',
'age': 'Age',
'feet': 'Feet',
'inches': 'Inches',
'ft': 'ft',
'in': 'in',
'weight_kg': 'Weight (kg)',
'gender': 'Gender:',
'male': 'Male',
'female': 'Female',
'activity_level': 'Activity Level:',
'track_todays_meals': 'Just had a Meal?',
'know_calories': 'Know Calories?',
'ai_predict': 'AI Predict',
'food_name': 'Food Name',
'calories_kcal': 'Calories (kcal)',
'amount_eg': 'Amount (e.g., 100g, 1 cup)',
'add_entry': 'Add to Calories Count',
'predicting': 'Predicting...',
'no_meals_logged': 'No meals logged today',
'todays_meals': 'Today\'s Meals',
'delete_entry': 'Delete Entry',
'remove_entry': 'Remove',
'consumed': 'Consumed',
'over': 'Over',
'enter_food_and_calories': 'Please enter food name and calories',
'enter_valid_calories': 'Please enter a valid calorie value',
'added': 'Added',
'enter_food_and_amount': 'Please enter food name and amount',
'ai_predicted': 'AI predicted',
'error_predicting': 'Error predicting calories',
'entry_deleted': 'Entry deleted',
'user': 'User',
'no_email': 'No email',
'hide_details': 'Hide Details',
'view_profile': 'View Profile',
'personal_information': 'Personal Information',
'first_name': 'First Name',
'last_name': 'Last Name',

// English
'of': 'of',
'no_instruction': 'No instruction provided',
'dish_ready': 'Your dish is ready to serve!',


// Bangla



  };

  // Bangla Strings
  static const Map<String, String> bn = {
    // Common
    'app_name': 'রেসিপি উইসপার',
    'ok': 'ঠিক আছে',
    'cancel': 'বাতিল',
    'save': 'সংরক্ষণ',
    'delete': 'মুছুন',
    'edit': 'সম্পাদনা',
    'search': 'খুঁজুন',
    
    // Auth
    'login': 'লগইন',
    'signup': 'সাইন আপ',
    'logout': 'লগআউট',
    'email': 'ইমেইল',
    'password': 'পাসওয়ার্ড',
    'forgot_password': 'পাসওয়ার্ড ভুলে গেছেন?',
    'dont_have_account': 'অ্যাকাউন্ট নেই? সাইন আপ করুন',
    'already_have_account': 'ইতিমধ্যে অ্যাকাউন্ট আছে? লগইন করুন',
    'login_success': 'লগইন সফল হয়েছে',
    'signup_success': 'সাইন আপ সফল হয়েছে',
    'login_failed': 'লগইন ব্যর্থ হয়েছে',
    'signup_failed': 'সাইন আপ ব্যর্থ হয়েছে',
    'password_reset_sent': 'পাসওয়ার্ড রিসেট ইমেইল পাঠানো হয়েছে',
    'enter_email_first': 'প্রথমে আপনার ইমেইল লিখুন',
    
    // Home
    'good_morning': 'সুপ্রভাত! 👋',
    'good_afternoon': 'শুভ অপরাহ্ন! 👋',
    'good_evening': 'শুভ সন্ধ্যা! 👋',
    'what_to_cook': 'আজ আপনি কী রান্না করতে চান?',
    'search_recipes': 'রেসিপি খুঁজুন...',
    'popular_recipes': 'জনপ্রিয় রেসিপি',
    
    // Navigation
    'home': 'হোম',
    'recipes': 'রেসিপি',
    'ai': 'এআই',
    'profile': 'প্রোফাইল',
    
    // Profile
    'settings': 'সেটিংস',
    'dark_theme': 'ডার্ক থিম',
    'english_language': 'ইংরেজি ভাষা',
    'account': 'অ্যাকাউন্ট',
    'preferences': 'পছন্দসমূহ',
    'edit_profile': 'প্রোফাইল সম্পাদনা',
    'display_name': 'প্রদর্শনের নাম',
    'change_password': 'পাসওয়ার্ড পরিবর্তন',
    'name_updated': 'নাম সফলভাবে আপডেট করা হয়েছে!',
    'error_updating_name': 'নাম আপডেট করতে ত্রুটি',
    'password_reset_dialog_title': 'পাসওয়ার্ড পরিবর্তন',
    'password_reset_dialog_message': 'আপনার ইমেইল ঠিকানায় একটি পাসওয়ার্ড রিসেট লিঙ্ক পাঠানো হবে।',
    'send_reset_link': 'রিসেট লিঙ্ক পাঠান',
    
    // Recipe
    'add_recipe': 'রেসিপি যোগ করুন',
    'edit_recipe': 'রেসিপি সম্পাদনা',
    'recipe_name': 'রেসিপির নাম',
    'recipe_description': 'বিবরণ',
    'ingredients': 'উপকরণ',
    'instructions': 'নির্দেশনা',
    'cooking_time': 'রান্নার সময়',
    'servings': 'পরিবেশন',
    'category': 'ক্যাটাগরি',
    'minutes': 'মিনিট',
    'recipe_added': 'রেসিপি সফলভাবে যোগ করা হয়েছে',
    'recipe_deleted': 'রেসিপি মুছে ফেলা হয়েছে',
    'recipe_updated': 'রেসিপি আপডেট করা হয়েছে',
    'no_recipes': 'কোনো রেসিপি পাওয়া যায়নি',
    'add_your_first': 'আপনার প্রথম রেসিপি যোগ করুন!',
    'recipe_details': 'রেসিপির বিবরণ',
    'add_ingredient': 'উপকরণ যোগ করুন',
    'add_instruction': 'নির্দেশনা যোগ করুন',
    'enter_ingredient': 'উপকরণ লিখুন',
    'enter_instruction': 'নির্দেশনা লিখুন',
    'step': 'ধাপ',
    'start_cooking': 'রান্না শুরু করুন',
    'resume_cooking': 'রান্না পুনরায় শুরু করুন',
    
    // AI
    'ai_suggestions': 'এআই পরামর্শ',
    'get_suggestion': 'পরামর্শ পান',
    'generating': 'তৈরি হচ্ছে...',
    'ai_assistant': 'এআই সহকারী',
    'type_message': 'আপনার বার্তা লিখুন...',
    'clear_chat': 'চ্যাট মুছুন',
    'chat_cleared': 'চ্যাট মুছে ফেলা হয়েছে! নতুন কথোপকথন শুরু করুন।',
    'ai_thinking': 'এআই চিন্তা করছে...',
    'how_to_use': 'কীভাবে ব্যবহার করবেন',
    'help': 'সাহায্য',
    'quick_actions': 'দ্রুত কর্ম',
    'start_chatting': 'চ্যাট শুরু করুন!',
    'personalized_recommendations': 'আপনার জন্য ব্যক্তিগত সুপারিশ',
    'create_new_recipe': 'একটি নতুন রেসিপি তৈরি করুন',
    'create_new_recipe_desc': 'কথোপকথনের মাধ্যমে রেসিপি যোগ করতে এআই সাহায্য করুক',
    'low_carb_dinner': 'কম কার্ব ডিনার আইডিয়া',
    'low_carb_dinner_desc': 'স্বাস্থ্যকর এবং সুস্বাদু খাবারের পরামর্শ',
    'quick_breakfast': 'দ্রুত নাস্তা রেসিপি',
    'quick_breakfast_desc': '১৫ মিনিটের কম সময়ে দিন শুরু করুন',
    'meal_prep': 'সপ্তাহের জন্য খাবার প্রস্তুতি',
    'meal_prep_desc': 'ব্যাচ রান্নার টিপস দিয়ে সময় বাঁচান',
    'mexican_cuisine': 'মেক্সিকান খাবারের রাত',
    'mexican_cuisine_desc': 'প্রামাণিক স্বাদ এবং ঐতিহ্যবাহী রেসিপি',
    'recipe_saved_tap': 'রেসিপি সংরক্ষিত! দেখতে ট্যাপ করুন',
    'got_it': 'বুঝেছি!',
    
    // Nutrition
    'nutrition': 'পুষ্টি',
    'calories': 'ক্যালোরি',
    'protein': 'প্রোটিন',
    'carbs': 'কার্বোহাইড্রেট',
    'fat': 'চর্বি',
    
    // Reminders
    'reminders': 'রিমাইন্ডার',
    'set_reminder': 'রিমাইন্ডার সেট করুন',
    'reminder_time': 'রিমাইন্ডার সময়',
    'reminder_set': 'রিমাইন্ডার সফলভাবে সেট করা হয়েছে',

    // Cooking timer
    'no_recipe': 'কোনো রেসিপি নেই',
    'no_active_timer': 'কোনো চলমান টাইমার নেই',
    'cooking': 'রান্না চলছে',
    'done': '✅ সম্পন্ন!',
    'pause': 'বিরতি',
    'resume': 'পুনরায় শুরু',
    'finish': 'শেষ',
    'stage_just_started': '🔥 শুরু হয়েছে...',
    'stage_heating_up': '🍳 গরম হচ্ছে...',
    'stage_cooking_nicely': '🥘 সুন্দরভাবে রান্না হচ্ছে...',
    'stage_getting_close': '⏳ প্রায় শেষ...',
    'stage_almost_done': '🍲 প্রায় সম্পন্ন...',
    'stage_ready_soon': '🍽 শীঘ্রই প্রস্তুত...',

    'previous': 'পূর্ববর্তী',
    'next': 'পরবর্তী',
    'stop': 'বন্ধ করুন',
    'stop_cooking_confirmation': 'আপনি কি রান্না বন্ধ করতে চান?',
    'no_instructions_available': 'কোন নির্দেশনা পাওয়া যায়নি',

    // Add to Bangla (bn) map:
'consumed_today': 'আজ খাওয়া হয়েছে',
'kcal': 'কিলোক্যালোরি',
'over_limit': 'সীমা অতিক্রম',
'remaining': 'অবশিষ্ট',
'view_diet_profile': 'ডায়েট প্রোফাইল দেখুন',
'diet_calorie_tracker': 'ডায়েট এবং ক্যালোরি ট্র্যাকার',
'height': 'উচ্চতা',
'daily_goal': 'দৈনিক লক্ষ্য',
'edit_diet_profile': 'ডায়েট প্রোফাইল সম্পাদনা',
'diet_profile': 'ডায়েট প্রোফাইল',
'age': 'বয়স',
'feet': 'ফুট',
'inches': 'ইঞ্চি',
'ft': 'ফুট',
'in': 'ইঞ্চি',
'weight_kg': 'ওজন (কেজি)',
'gender': 'লিঙ্গ:',
'male': 'পুরুষ',
'female': 'মহিলা',
'activity_level': 'কার্যকলাপের স্তর:',
'track_todays_meals': 'আজকের খাবার ট্র্যাক করুন',
'know_calories': 'ক্যালোরি জানি',
'ai_predict': 'এআই অনুমান', 
'food_name': 'খাবারের নাম',
'calories_kcal': 'ক্যালোরি (কিলোক্যালোরি)',
'amount_eg': 'পরিমাণ (যেমন, ১০০ গ্রাম, ১ কাপ)',
'add_entry': 'এন্ট্রি যোগ করুন',
'predicting': 'পূর্বাভাস দিচ্ছে...',
'no_meals_logged': 'আজ কোনো খাবার লগ করা হয়নি',
'todays_meals': 'আজকের খাবার',
'delete_entry': 'এন্ট্রি মুছুন',
'remove_entry': 'সরান',
'consumed': 'খাওয়া হয়েছে',
'over': 'অতিরিক্ত',
'enter_food_and_calories': 'অনুগ্রহ করে খাবারের নাম এবং ক্যালোরি লিখুন',
'enter_valid_calories': 'অনুগ্রহ করে একটি বৈধ ক্যালোরি মান লিখুন',
'added': 'যোগ করা হয়েছে',
'enter_food_and_amount': 'অনুগ্রহ করে খাবারের নাম এবং পরিমাণ লিখুন',
'ai_predicted': 'এআই অনুমান', 
'error_predicting': 'ক্যালোরি পূর্বাভাস করতে ত্রুটি',
'entry_deleted': 'এন্ট্রি মুছে ফেলা হয়েছে',
'user': 'ব্যবহারকারী',
'no_email': 'কোনো ইমেইল নেই',
'hide_details': 'বিবরণ লুকান',
'view_profile': 'প্রোফাইল দেখুন',
'personal_information': 'ব্যক্তিগত তথ্য',
'first_name': 'নামের প্রথম অংশ',
'last_name': 'নামের শেষ অংশ',

'of': 'এর',
'no_instruction': 'কোনো নির্দেশনা প্রদান করা হয়নি',
'dish_ready': 'আপনার খাবার পরিবেশনের জন্য প্রস্তুত!',



    
  };

  static Map<String, String> getStrings(String languageCode) {
    switch (languageCode) {
      case 'bn':
        return bn;
      case 'en':
      default:
        return en;
    }
  }
}